package serve

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/varwof/core/internal"
	"github.com/varwof/core/internal/ca"
	"github.com/varwof/engine/db"
	"github.com/varwof/core/internal/i18n"
)

var testBundle = i18n.NewBundle()

// adminTestCert builds a management certificate with PA extension (OU=role + grants),
// for mTLS testing (cert-first: permissions = certificate PA grants).
func adminTestCert(t *testing.T, ou string, caps ...string) (*x509.Certificate, crypto.Signer) {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	var grants []ca.Capability
	for _, c := range caps {
		scheme, action := c, c
		if i := strings.Index(c, ":"); i > 0 {
			scheme, action = c[:i], c[i+1:]
		}
		grants = append(grants, ca.Capability{SchemeId: scheme, CapabilityId: action})
	}
	paExt, err := ca.BuildPrincipalAuthorizationExtension(ca.PrincipalAuthorizationConfig{Grants: grants})
	if err != nil {
		t.Fatal(err)
	}
	tmpl := &x509.Certificate{
		SerialNumber: big.NewInt(time.Now().UnixNano()),
		Subject: pkix.Name{
			CommonName:         "test-admin",
			OrganizationalUnit: []string{ou},
		},
		NotBefore:   time.Now().Add(-1 * time.Hour),
		NotAfter:    time.Now().Add(time.Hour),
		KeyUsage:    x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
		ExtraExtensions: []pkix.Extension{paExt},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatal(err)
	}
	return cert, key
}

// newTestMTLSServer starts a test server requiring client mTLS certificates,
// trusting certificates generated by adminTestCert (self-signed, added to ClientCAs).
func newTestMTLSServer(t *testing.T, h http.Handler, certs ...*x509.Certificate) *httptest.Server {
	t.Helper()
	pool := x509.NewCertPool()
	for _, c := range certs {
		pool.AddCert(c)
	}
	ts := httptest.NewUnstartedServer(h)
	ts.TLS = &tls.Config{ClientAuth: tls.RequireAndVerifyClientCert, ClientCAs: pool}
	ts.StartTLS()
	t.Cleanup(ts.Close)
	return ts
}

// authedMTLSGet sends a GET request with mTLS management certificate.
func authedMTLSGet(t *testing.T, client *http.Client, ts *httptest.Server, path string) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodGet, ts.URL+path, nil)
	if err != nil {
		t.Fatal(err)
	}
	resp, err := client.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

// authedMTLSPost sends a POST request with mTLS management certificate.
func authedMTLSPost(t *testing.T, client *http.Client, ts *httptest.Server, path, ctype string, body io.Reader) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, ts.URL+path, body)
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("Content-Type", ctype)
	resp, err := client.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

// authedMTLSDel sends a DELETE request with mTLS management certificate.
func authedMTLSDel(t *testing.T, client *http.Client, ts *httptest.Server, path string) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodDelete, ts.URL+path, nil)
	if err != nil {
		t.Fatal(err)
	}
	resp, err := client.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

// mtlsAdminFixture is a combined "mTLS management server + corresponding client"
// for HTTP tests requiring admin permissions (cert-first: permissions come from certificate PA grants).
type mtlsAdminFixture struct {
	Server *httptest.Server
	Client *http.Client
}

// newMTLSAdminFixture builds an admin-role management certificate with specified grants,
// starts an mTLS test server trusting that certificate, and returns a client with the certificate.
func newMTLSAdminFixture(t *testing.T, h http.Handler, caps ...string) *mtlsAdminFixture {
	t.Helper()
	return newMTLSCertFixture(t, h, "admin", caps...)
}

// newMTLSSuperAdminFixture builds a superadmin-role management certificate with specified grants.
func newMTLSSuperAdminFixture(t *testing.T, h http.Handler, caps ...string) *mtlsAdminFixture {
	t.Helper()
	return newMTLSCertFixture(t, h, "SuperAdmin", caps...)
}

// newMTLSCertFixture builds a management certificate with specified OU role + grants and starts an mTLS test server.
func newMTLSCertFixture(t *testing.T, h http.Handler, ou string, caps ...string) *mtlsAdminFixture {
	t.Helper()
	cert, key := adminTestCert(t, ou, caps...)
	ts := newTestMTLSServer(t, h, cert)

	client := ts.Client()
	leaf, err := tls.X509KeyPair([]byte(pemCert(cert)), []byte(pemKey(key)))
	if err != nil {
		t.Fatal(err)
	}
	if tr, ok := client.Transport.(*http.Transport); ok {
		tr.TLSClientConfig.Certificates = []tls.Certificate{leaf}
	}
	return &mtlsAdminFixture{Server: ts, Client: client}
}

func newTestDB(t *testing.T) *db.DB {
	t.Helper()
	dir := t.TempDir()
	d, err := db.Open(filepath.Join(dir, "test.db"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { d.Close() })
	return d
}

func seedAdmin(t *testing.T, d *db.DB) {
	t.Helper()
	salt, _ := db.GenerateSalt()
	if err := d.CreateUser("admin", db.HashPassword("admin", salt), salt, "admin"); err != nil {
		t.Fatal(err)
	}
	salt2, _ := db.GenerateSalt()
	if err := d.CreateUser("superadmin", db.HashPassword("superadmin", salt2), salt2, "superadmin"); err != nil {
		t.Fatal(err)
	}
}

func newTestCA(t *testing.T, name string) (*x509.Certificate, crypto.Signer) {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tmpl := &x509.Certificate{
		SerialNumber:          big.NewInt(1),
		Subject:               pkix.Name{CommonName: name},
		NotBefore:             time.Now().Add(-1 * time.Hour),
		NotAfter:              time.Now().Add(10 * 365 * 24 * time.Hour),
		BasicConstraintsValid: true,
		IsCA:                  true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatal(err)
	}
	return cert, key
}

func newTestServer(t *testing.T) http.Handler {
	t.Helper()
	d := newTestDB(t)
	seedAdmin(t, d)

	caCert, caKey := newTestCA(t, "test-ca")
	d.InsertCAMeta(&db.CAMeta{
		Name:         "test-ca",
		CertDER:      caCert.Raw,
		Subject:      caCert.Subject.String(),
		NotBefore:    caCert.NotBefore,
		NotAfter:     caCert.NotAfter,
		KeyAlgorithm: "ecdsa-p256",
		Fingerprint:  db.Fingerprint(caCert.Raw),
	})

	dir := t.TempDir()
	certPath := filepath.Join(dir, "ca.pem")
	keyPath := filepath.Join(dir, "ca.key")
	writePEMFile(t, certPath, "CERTIFICATE", caCert.Raw)
	keyDER, _ := x509.MarshalPKCS8PrivateKey(caKey)
	writePEMFile(t, keyPath, "PRIVATE KEY", keyDER)

	cfg := internal.DefaultConfig()
	cfg.Serve.Addr = ":0"
	cfg.Serve.Static = ""
	cfg.Defaults.CA = "test-ca"
	cfg.TSA.SignerCert = ""
	cfg.TSA.SignerKey = ""
	cfg.OCSP.SignerCert = ""
	cfg.OCSP.SignerKey = ""
	cfg.CAs = map[string]internal.CAConfig{
		"test-ca": {Cert: certPath, Key: keyPath},
	}

	tsaDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/timestamp-reply")
		w.Write([]byte("tsa-ok"))
	})
	ocspDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/ocsp-response")
		w.Write([]byte("ocsp-ok"))
	})

	return WrapHandler(NewFull(&cfg, d, testBundle, tsaDummy, ocspDummy))
}

func writePEMFile(t *testing.T, path, typ string, der []byte) {
	t.Helper()
	if err := os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: typ, Bytes: der}), 0644); err != nil {
		t.Fatal(err)
	}
}

func authedGet(t *testing.T, ts *httptest.Server, path string) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodGet, ts.URL+path, nil)
	if err != nil {
		t.Fatal(err)
	}
	req.SetBasicAuth("admin", "admin")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

func authedPost(t *testing.T, ts *httptest.Server, path, ctype string, body io.Reader) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, ts.URL+path, body)
	if err != nil {
		t.Fatal(err)
	}
	req.SetBasicAuth("admin", "admin")
	req.Header.Set("Content-Type", ctype)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

func authedGetSuperAdmin(t *testing.T, ts *httptest.Server, path string) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodGet, ts.URL+path, nil)
	if err != nil {
		t.Fatal(err)
	}
	req.SetBasicAuth("superadmin", "superadmin")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

func authedPostSuperAdmin(t *testing.T, ts *httptest.Server, path, ctype string, body io.Reader) *http.Response {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, ts.URL+path, body)
	if err != nil {
		t.Fatal(err)
	}
	req.SetBasicAuth("superadmin", "superadmin")
	req.Header.Set("Content-Type", ctype)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	return resp
}

func TestServeTSARoute(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/tsa", "application/timestamp-query", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if resp.Header.Get("Content-Type") != "application/timestamp-reply" {
		t.Fatalf("unexpected content-type: %s", resp.Header.Get("Content-Type"))
	}
}

func TestServeOCSPRoute(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/ocsp", "application/ocsp-request", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if resp.Header.Get("Content-Type") != "application/ocsp-response" {
		t.Fatalf("unexpected content-type: %s", resp.Header.Get("Content-Type"))
	}
}

func TestServeAPICAs(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/cas")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var list []jsonCA
	if err := json.NewDecoder(resp.Body).Decode(&list); err != nil {
		t.Fatal(err)
	}
	if len(list) != 1 {
		t.Fatalf("expected 1 CA, got %d", len(list))
	}
	if list[0].Name != "test-ca" {
		t.Fatalf("expected test-ca, got %q", list[0].Name)
	}
}

func TestServeAPICA(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/ca/test-ca")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var ca jsonCA
	if err := json.NewDecoder(resp.Body).Decode(&ca); err != nil {
		t.Fatal(err)
	}
	if ca.Name != "test-ca" {
		t.Fatalf("expected test-ca, got %q", ca.Name)
	}
	if ca.CertPEM == "" {
		t.Fatal("expected non-empty cert_pem")
	}
}

func TestServeAPICANotFound(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/ca/nonexistent")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", resp.StatusCode)
	}
}

func TestServeAPICerts(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/certs")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var list []jsonCert
	if err := json.NewDecoder(resp.Body).Decode(&list); err != nil {
		t.Fatal(err)
	}
}

func TestServeAPICRL(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/crl/test-ca")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if resp.Header.Get("Content-Type") != "application/pkix-crl" {
		t.Fatalf("unexpected content-type: %s", resp.Header.Get("Content-Type"))
	}
}

func TestServeAPICRLNoKey(t *testing.T) {
	d := newTestDB(t)
	seedAdmin(t, d)
	caCert, _ := newTestCA(t, "nokey-ca")
	d.InsertCAMeta(&db.CAMeta{
		Name:         "nokey-ca",
		CertDER:      caCert.Raw,
		Subject:      caCert.Subject.String(),
		NotBefore:    caCert.NotBefore,
		NotAfter:     caCert.NotAfter,
		KeyAlgorithm: "ecdsa-p256",
		Fingerprint:  db.Fingerprint(caCert.Raw),
	})

	cfg := internal.DefaultConfig()
	cfg.Serve.Addr = ":0"

	tsaDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})
	ocspDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})

	srv := NewFull(&cfg, d, testBundle, tsaDummy, ocspDummy)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/crl/nokey-ca")
	if resp.StatusCode != http.StatusInternalServerError {
		t.Fatalf("expected 500 for missing key, got %d", resp.StatusCode)
	}
}

func TestServeWebIndex(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if resp.Header.Get("Content-Type") != "text/html; charset=utf-8" {
		t.Fatalf("unexpected content-type: %s", resp.Header.Get("Content-Type"))
	}
}

func TestServeWebCAs(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/cas")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeWebCADetail(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/ca/test-ca")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeStaticCSS(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Get(ts.URL + "/pki/pki.css")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200 for static file, got %d", resp.StatusCode)
	}
}

func TestServeNotFound(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Get(ts.URL + "/nonexistent")
	if err != nil {
		t.Fatal(err)
	}
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", resp.StatusCode)
	}
}

func TestServeTSAByMIME(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/", "application/timestamp-query", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if resp.Header.Get("Content-Type") != "application/timestamp-reply" {
		t.Fatalf("unexpected content-type: %s", resp.Header.Get("Content-Type"))
	}
}

func TestServeOCSPByMIME(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/", "application/ocsp-request", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if resp.Header.Get("Content-Type") != "application/ocsp-response" {
		t.Fatalf("unexpected content-type: %s", resp.Header.Get("Content-Type"))
	}
}

func TestServeRootBadMIME(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/", "application/json", nil)
	if err != nil {
		t.Fatal(err)
	}
	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", resp.StatusCode)
	}
}

func TestServeTimestampRoute(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/timestamp", "application/timestamp-query", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestAPIErrorJSON(t *testing.T) {
	w := httptest.NewRecorder()
	apiErrorJSON(w, http.StatusBadRequest, "bad request", "detail text")
	if w.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", w.Code)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/json" {
		t.Fatalf("expected json, got %q", ct)
	}
	var e apiErr
	json.NewDecoder(w.Body).Decode(&e)
	if e.Code != 400 || e.Message != "bad request" || e.Detail != "detail text" {
		t.Fatalf("unexpected response: %+v", e)
	}
}

func TestAPIOK(t *testing.T) {
	w := httptest.NewRecorder()
	apiOK(w, map[string]string{"hello": "world"})
	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", w.Code)
	}
	var m map[string]string
	json.NewDecoder(w.Body).Decode(&m)
	if m["hello"] != "world" {
		t.Fatalf("expected world, got %q", m["hello"])
	}
}

func TestWantsCSV(t *testing.T) {
	r, _ := http.NewRequest("GET", "/api/certs?format=csv", nil)
	if !wantsCSV(r) {
		t.Fatal("expected wantsCSV=true for format=csv")
	}

	r2, _ := http.NewRequest("GET", "/api/certs", nil)
	r2.Header.Set("Accept", "text/csv")
	if !wantsCSV(r2) {
		t.Fatal("expected wantsCSV=true for Accept text/csv")
	}

	r3, _ := http.NewRequest("GET", "/api/certs", nil)
	if wantsCSV(r3) {
		t.Fatal("expected wantsCSV=false for plain GET")
	}
}

func TestCertToJSON(t *testing.T) {
	now := time.Now()
	reason := 1
	rec := &db.CertRecord{
		SerialNumber: "ABC123",
		CAName:       "test-ca",
		Status:       "V",
		Subject:      "CN=test,O=test",
		CommonName:   "test",
		NotBefore:    now,
		NotAfter:     now.Add(365 * 24 * time.Hour),
		Fingerprint:  "abcdef",
		CertDER:      []byte("fake-cert-der-here"),
	}

	j := certToJSON(rec, false)
	if j.SerialNumber != "ABC123" {
		t.Fatalf("expected ABC123, got %q", j.SerialNumber)
	}
	if j.CertPEM != "" {
		t.Fatal("expected empty CertPEM when includePEM=false")
	}

	j2 := certToJSON(rec, true)
	if j2.CertPEM == "" {
		t.Fatal("expected non-empty CertPEM when includePEM=true")
	}

	revokedAt := now.Add(-24 * time.Hour)
	rec.Status = "R"
	rec.RevokedAt = &revokedAt
	rec.RevokeReason = &reason
	j3 := certToJSON(rec, false)
	if j3.RevokedAt == nil || *j3.RevokedAt == "" {
		t.Fatal("expected revoked_at to be set")
	}
	if j3.RevokeReason == nil || *j3.RevokeReason != 1 {
		t.Fatalf("expected revoke_reason=1, got %v", j3.RevokeReason)
	}
}

func TestCAMetaToJSON(t *testing.T) {
	now := time.Now()
	meta := &db.CAMeta{
		Name:         "test-ca",
		Subject:      "CN=test-ca,O=test",
		NotBefore:    now,
		NotAfter:     now.Add(10 * 365 * 24 * time.Hour),
		KeyAlgorithm: "ecdsa-p256",
		Fingerprint:  "abcd1234",
		CertDER:      []byte("fake-cert-der"),
	}

	j := caMetaToJSON(meta)
	if j.Name != "test-ca" {
		t.Fatalf("expected test-ca, got %q", j.Name)
	}
	if j.CertPEM == "" {
		t.Fatal("expected non-empty cert_pem")
	}
}

func TestWriteCSV(t *testing.T) {
	w := httptest.NewRecorder()
	header := []string{"name", "value"}
	rows := [][]string{{"a", "1"}, {"b", "2"}}
	writeCSV(w, header, rows, "test.csv")

	if ct := w.Header().Get("Content-Type"); ct != "text/csv; charset=utf-8" {
		t.Fatalf("expected csv content-type, got %q", ct)
	}
	body := w.Body.String()
	if !strings.Contains(body, "name,value") {
		t.Fatal("csv missing header")
	}
	if !strings.Contains(body, "a,1") || !strings.Contains(body, "b,2") {
		t.Fatal("csv missing data rows")
	}
}

func TestServeAPICSV(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/cas?format=csv")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); !strings.Contains(ct, "text/csv") {
		t.Fatalf("expected csv, got %q", ct)
	}
}

func TestServeAPICertsCSV(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/certs?format=csv")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeAPICertNotFound(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/cert/test-ca/NONEXISTENT")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", resp.StatusCode)
	}
}

func TestServeAPICertPEM(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// First issue a cert so we have one
	d, _ := db.Open("") // just use the server's db via API

	req, _ := http.NewRequest("GET", ts.URL+"/api/cert/test-ca/none", nil)
	req.SetBasicAuth("admin", "admin")
	req.Header.Set("Accept", "application/x-pem-file")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	_ = d // unused, cert not found is fine
}

func TestServeAPIStats(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/stats")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var stats Stats
	if err := json.NewDecoder(resp.Body).Decode(&stats); err != nil {
		t.Fatal(err)
	}
	if stats.TotalCAs != 1 {
		t.Fatalf("expected 1 CA, got %d", stats.TotalCAs)
	}
}

func TestServeAPIBatch(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	body := `{"requests":[{"cn":"batch1.example.com","profile":"tls-server"},{"cn":"batch2.example.com","profile":"tls-server"}]}`
	resp := authedPost(t, ts, "/api/certs/batch", "application/json", strings.NewReader(body))
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var results []batchRespItem
	json.NewDecoder(resp.Body).Decode(&results)
	if len(results) != 2 {
		t.Fatalf("expected 2 results, got %d", len(results))
	}
	for _, r := range results {
		if r.Status != "ok" {
			t.Fatalf("expected ok for %s, got %s: %s", r.CN, r.Status, r.Error)
		}
		if r.Serial == "" {
			t.Fatalf("expected non-empty serial for %s", r.CN)
		}
	}
}

func TestServeAPIBatchNoAuth(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	body := `{"requests":[{"cn":"test.example.com"}]}`
	resp, err := http.Post(ts.URL+"/api/certs/batch", "application/json", strings.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d", resp.StatusCode)
	}
}

func TestServeAPIBatchWrongContentType(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedPost(t, ts, "/api/certs/batch", "text/plain", strings.NewReader("{}"))
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusUnsupportedMediaType {
		t.Fatalf("expected 415, got %d", resp.StatusCode)
	}
}

func TestServeAPIWebhooks(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// List (empty)
	resp := authedGet(t, ts, "/api/webhooks")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var list []interface{}
	json.NewDecoder(resp.Body).Decode(&list)
	if len(list) != 0 {
		t.Fatalf("expected 0 webhooks, got %d", len(list))
	}

	// Create
	createBody := `{"url":"https://hook.example.com/notify","events":"issue,revoke"}`
	resp2 := authedPost(t, ts, "/api/webhooks", "application/json", strings.NewReader(createBody))
	defer resp2.Body.Close()
	if resp2.StatusCode != http.StatusCreated {
		t.Fatalf("expected 201, got %d", resp2.StatusCode)
	}
	var sub map[string]interface{}
	json.NewDecoder(resp2.Body).Decode(&sub)
	if sub["url"] != "https://hook.example.com/notify" {
		t.Fatalf("expected url to match, got %v", sub["url"])
	}

	// Create missing url
	resp3 := authedPost(t, ts, "/api/webhooks", "application/json", strings.NewReader(`{"events":"issue"}`))
	defer resp3.Body.Close()
	if resp3.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", resp3.StatusCode)
	}

	// Create wrong content type
	resp4 := authedPost(t, ts, "/api/webhooks", "text/plain", strings.NewReader(`{}`))
	defer resp4.Body.Close()
	if resp4.StatusCode != http.StatusUnsupportedMediaType {
		t.Fatalf("expected 415, got %d", resp4.StatusCode)
	}

	// Delete
	id := int(sub["id"].(float64))
	resp5 := authedGet(t, ts, fmt.Sprintf("/api/webhooks?id=%d", id))
	defer resp5.Body.Close()
	// DELETE via query param + GET (the handler checks method)
	req, _ := http.NewRequest("DELETE", fmt.Sprintf("%s/api/webhooks?id=%d", ts.URL, id), nil)
	req.SetBasicAuth("admin", "admin")
	resp6, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp6.Body.Close()
	if resp6.StatusCode != http.StatusNoContent {
		t.Fatalf("expected 204, got %d", resp6.StatusCode)
	}
}

func TestServeAPICATree(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/cas/tree")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var roots []map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&roots)
	if len(roots) != 1 {
		t.Fatalf("expected 1 root CA, got %d", len(roots))
	}
	if roots[0]["name"] != "test-ca" {
		t.Fatalf("expected test-ca, got %q", roots[0]["name"])
	}
}

func TestServeDashboard(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/dashboard")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeTopology(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/topology")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeAPIV1(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/v1/cas")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeWebCerts(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/certs")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeWebCertDetail(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// No certs exist yet, but page should still render
	resp := authedGet(t, ts, "/cert/test-ca/NONEXISTENT")
	defer resp.Body.Close()
}

func TestServeHealthz(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Get(ts.URL + "/healthz")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var hs map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&hs)
	if hs["status"] != "ok" {
		t.Fatalf("expected status ok, got %v", hs["status"])
	}
	if hs["db"] != "ok" {
		t.Fatalf("expected db ok, got %v", hs["db"])
	}
}

func TestServeReadyz(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Get(ts.URL + "/readyz")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

func TestServeAPINotFound(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/v1/nonexistent")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", resp.StatusCode)
	}
}

func TestServeHealthzDegraded(t *testing.T) {
	d := newTestDB(t)
	caCert, _ := newTestCA(t, "degraded-ca")
	d.InsertCAMeta(&db.CAMeta{
		Name:         "degraded-ca",
		CertDER:      caCert.Raw,
		Subject:      caCert.Subject.String(),
		NotBefore:    caCert.NotBefore,
		NotAfter:     caCert.NotAfter,
		KeyAlgorithm: "ecdsa-p256",
		Fingerprint:  db.Fingerprint(caCert.Raw),
	})

	cfg := internal.DefaultConfig()
	cfg.Serve.Addr = ":0"
	cfg.TSA.SignerCert = "/nonexistent/tsa-cert.pem"

	tsaDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})
	ocspDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})

	srv := NewFull(&cfg, d, testBundle, tsaDummy, ocspDummy)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp, err := http.Get(ts.URL + "/healthz")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	var hs map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&hs)
	if hs["status"] != "degraded" {
		t.Fatalf("expected degraded status, got %v", hs["status"])
	}
}

func TestServeRatelimit(t *testing.T) {
	d := newTestDB(t)
	seedAdmin(t, d)

	caCert, caKey := newTestCA(t, "rl-ca")
	d.InsertCAMeta(&db.CAMeta{
		Name: "rl-ca", CertDER: caCert.Raw, Subject: caCert.Subject.String(),
		NotBefore: caCert.NotBefore, NotAfter: caCert.NotAfter,
		KeyAlgorithm: "ecdsa-p256", Fingerprint: db.Fingerprint(caCert.Raw),
	})
	dir := t.TempDir()
	certPath := filepath.Join(dir, "ca.pem")
	keyPath := filepath.Join(dir, "ca.key")
	writePEMFile(t, certPath, "CERTIFICATE", caCert.Raw)
	keyDER, _ := x509.MarshalPKCS8PrivateKey(caKey)
	writePEMFile(t, keyPath, "PRIVATE KEY", keyDER)

	cfg := internal.DefaultConfig()
	cfg.Serve.Addr = ":0"
	cfg.RateLimit.Rate = 1.0
	cfg.RateLimit.Burst = 0
	cfg.CAs = map[string]internal.CAConfig{"rl-ca": {Cert: certPath, Key: keyPath}}

	tsaDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})
	ocspDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})

	srv := NewFull(&cfg, d, testBundle, tsaDummy, ocspDummy)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// First request — allowed
	resp := authedGet(t, ts, "/api/cas")
	resp.Body.Close()

	// Second request, same IP — might be rate limited (depending on burst=0)
	resp2 := authedGet(t, ts, "/api/cas")
	resp2.Body.Close()
}

func TestCollectStats(t *testing.T) {
	// Test Stats struct and collectStats directly
	d := newTestDB(t)
	seedAdmin(t, d)

	caCert, caKey := newTestCA(t, "stats-ca")
	d.InsertCAMeta(&db.CAMeta{
		Name: "stats-ca", CertDER: caCert.Raw, Subject: caCert.Subject.String(),
		NotBefore: caCert.NotBefore, NotAfter: caCert.NotAfter,
		KeyAlgorithm: "ecdsa-p256", Fingerprint: db.Fingerprint(caCert.Raw),
	})
	dir := t.TempDir()
	certPath := filepath.Join(dir, "ca.pem")
	keyPath := filepath.Join(dir, "ca.key")
	writePEMFile(t, certPath, "CERTIFICATE", caCert.Raw)
	keyDER, _ := x509.MarshalPKCS8PrivateKey(caKey)
	writePEMFile(t, keyPath, "PRIVATE KEY", keyDER)

	cfg := internal.DefaultConfig()
	cfg.Serve.Addr = ":0"
	cfg.Serve.Static = ""
	cfg.CAs = map[string]internal.CAConfig{"stats-ca": {Cert: certPath, Key: keyPath}}

	tsaDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})
	ocspDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})

	s := NewFull(&cfg, d, testBundle, tsaDummy, ocspDummy)

	st := s.collectStats()
	if st.TotalCAs != 1 {
		t.Fatalf("expected 1 CA, got %d", st.TotalCAs)
	}
	if st.TotalCerts != 0 {
		t.Fatalf("expected 0 certs, got %d", st.TotalCerts)
	}
	if st.UpdatedAt == "" {
		t.Fatal("expected non-empty UpdatedAt")
	}
}

func TestCertRecordToRow(t *testing.T) {
	now := time.Now()
	rec := &db.CertRecord{
		SerialNumber: "SN001",
		CAName:       "ca1",
		Status:       "V",
		CommonName:   "valid.test",
		NotBefore:    now,
		NotAfter:     now.Add(365 * 24 * time.Hour),
	}
	row := certRecordToRow(rec)
	if row.StatusBadge != "valid" {
		t.Fatalf("expected valid badge, got %q", row.StatusBadge)
	}

	rec.Status = "R"
	row = certRecordToRow(rec)
	if row.StatusBadge != "revoked" {
		t.Fatalf("expected revoked badge, got %q", row.StatusBadge)
	}

	rec.Status = "E"
	row = certRecordToRow(rec)
	if row.StatusBadge != "expired" {
		t.Fatalf("expected expired badge, got %q", row.StatusBadge)
	}
}

func TestCountCerts(t *testing.T) {
	d := newTestDB(t)
	_ = d

	// Use server + issued certs
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// Issue a cert via batch so we have data
	body := `{"requests":[{"cn":"count.test.example.com","profile":"tls-server"}]}`
	resp := authedPost(t, ts, "/api/certs/batch", "application/json", strings.NewReader(body))
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("batch issue failed: %d", resp.StatusCode)
	}
	resp2 := authedGet(t, ts, "/api/certs")
	defer resp2.Body.Close()
	var list []jsonCert
	json.NewDecoder(resp2.Body).Decode(&list)
	if len(list) != 1 {
		t.Fatalf("expected 1 cert after batch, got %d", len(list))
	}
}

func TestServePDFReport(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	resp := authedGet(t, ts, "/api/certs/report.pdf?ca=test-ca")
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "application/pdf" {
		t.Fatalf("expected application/pdf, got %q", ct)
	}
}

func TestServeAPIWebhookGetDelete(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// Delete with no id
	req, _ := http.NewRequest("DELETE", ts.URL+"/api/webhooks", nil)
	req.SetBasicAuth("admin", "admin")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400 for missing id, got %d", resp.StatusCode)
	}

	// Delete with invalid id
	req2, _ := http.NewRequest("DELETE", ts.URL+"/api/webhooks?id=abc", nil)
	req2.SetBasicAuth("admin", "admin")
	resp2, err := http.DefaultClient.Do(req2)
	if err != nil {
		t.Fatal(err)
	}
	defer resp2.Body.Close()
	if resp2.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400 for invalid id, got %d", resp2.StatusCode)
	}
}

func TestRBACAuth(t *testing.T) {
	d := newTestDB(t)
	caCert, caKey := newTestCA(t, "test-ca")
	d.InsertCAMeta(&db.CAMeta{
		Name:         "test-ca",
		CertDER:      caCert.Raw,
		Subject:      caCert.Subject.String(),
		NotBefore:    caCert.NotBefore,
		NotAfter:     caCert.NotAfter,
		KeyAlgorithm: "ecdsa-p256",
		Fingerprint:  db.Fingerprint(caCert.Raw),
	})
	dir := t.TempDir()
	certPath := filepath.Join(dir, "ca.pem")
	keyPath := filepath.Join(dir, "ca.key")
	writePEMFile(t, certPath, "CERTIFICATE", caCert.Raw)
	keyDER, _ := x509.MarshalPKCS8PrivateKey(caKey)
	writePEMFile(t, keyPath, "PRIVATE KEY", keyDER)

	salt, _ := db.GenerateSalt()
	if err := d.CreateUser("testuser", db.HashPassword("secret", salt), salt, "auditor"); err != nil {
		t.Fatal(err)
	}

	cfg := internal.DefaultConfig()
	cfg.Serve.Addr = ":0"
	cfg.Serve.Static = ""
	cfg.CAs = map[string]internal.CAConfig{
		"test-ca": {Cert: certPath, Key: keyPath},
	}

	tsaDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/timestamp-reply")
		w.Write([]byte("tsa-ok"))
	})
	ocspDummy := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/ocsp-response")
		w.Write([]byte("ocsp-ok"))
	})

	srv := NewFull(&cfg, d, testBundle, tsaDummy, ocspDummy)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	// Without auth — should get 401
	resp, err := http.Get(ts.URL + "/api/cas")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("expected 401 without auth, got %d", resp.StatusCode)
	}

	// With wrong password — should get 401
	req, _ := http.NewRequest(http.MethodGet, ts.URL+"/api/cas", nil)
	req.SetBasicAuth("testuser", "wrong")
	resp, err = http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("expected 401 with wrong password, got %d", resp.StatusCode)
	}

	// With correct auth — should get 200 (auditor can access /api/cas)
	req, _ = http.NewRequest(http.MethodGet, ts.URL+"/api/cas", nil)
	req.SetBasicAuth("testuser", "secret")
	resp, err = http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200 with correct auth, got %d", resp.StatusCode)
	}

	// Auditor trying /api/certs — should get 403 (needs operator)
	req, _ = http.NewRequest(http.MethodGet, ts.URL+"/api/certs", nil)
	req.SetBasicAuth("testuser", "secret")
	resp, err = http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200 for auditor on /api/certs, got %d", resp.StatusCode)
	}

	// Health endpoint should be public
	resp, err = http.Get(ts.URL + "/healthz")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200 on /healthz without auth, got %d", resp.StatusCode)
	}

	// Bearer token auth
	token, err := d.CreateAPIToken(1, "test-token", "")
	if err != nil {
		t.Fatal(err)
	}
	req, _ = http.NewRequest(http.MethodGet, ts.URL+"/api/cas", nil)
	req.Header.Set("Authorization", "Bearer "+token.Token)
	resp, err = http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200 with bearer token, got %d", resp.StatusCode)
	}
}

func TestServeSwaggerHTML(t *testing.T) {
	s := &Server{}
	w := httptest.NewRecorder()
	r := httptest.NewRequest(http.MethodGet, "/swagger/", nil)
	s.serveSwagger(w, r)
	resp := w.Result()
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "text/html; charset=utf-8" {
		t.Fatalf("expected text/html, got %s", ct)
	}
	body, _ := io.ReadAll(resp.Body)
	if !strings.Contains(string(body), "swagger-ui") {
		t.Fatal("expected swagger-ui in body")
	}
}

func TestServeSwaggerYAML(t *testing.T) {
	dir := t.TempDir()
	orig, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(orig)
	if err := os.WriteFile("openapi.yaml", []byte("openapi: 3.0.0"), 0644); err != nil {
		t.Fatal(err)
	}

	s := &Server{}
	w := httptest.NewRecorder()
	r := httptest.NewRequest(http.MethodGet, "/swagger/openapi.yaml", nil)
	s.serveSwagger(w, r)
	resp := w.Result()
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "text/yaml; charset=utf-8" {
		t.Fatalf("expected text/yaml, got %s", ct)
	}
	body, _ := io.ReadAll(resp.Body)
	if !strings.Contains(string(body), "openapi: 3.0.0") {
		t.Fatal("expected openapi.yaml content")
	}
}

// ---------- Server helper tests ----------

func TestNewPublic(t *testing.T) {
	cfg := &internal.Config{}
	d := newTestDB(t)
	s := NewPublic(cfg, d, testBundle)
	if !s.publicOnly {
		t.Fatal("expected publicOnly")
	}
	if s.getConfig() != cfg {
		t.Fatal("config mismatch")
	}
	if s.getDB() != d {
		t.Fatal("db mismatch")
	}
}

func TestHandlerGetters(t *testing.T) {
	s := &Server{}
	// Without any handler set, should return NotFoundHandler
	h := s.ocspHandler()
	if h == nil {
		t.Fatal("expected non-nil handler")
	}
}

func TestHandlerSetters(t *testing.T) {
	s := &Server{}
	d := newTestDB(t)
	h1 := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(201) })
	h2 := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { w.WriteHeader(202) })
	s.Reload(&internal.Config{}, d, h1, h2)

	// Verify handlers work via ServeHTTP
	ts := httptest.NewServer(s)
	defer ts.Close()

	for _, tc := range []struct{ path, ct string; want int }{
		{"/tsa", "", 201},
		{"/ocsp", "", 202},
		{"/", "application/timestamp-query", 201},
		{"/", "application/ocsp-request", 202},
	} {
		req, _ := http.NewRequest(http.MethodPost, ts.URL+tc.path, nil)
		if tc.ct != "" {
			req.Header.Set("Content-Type", tc.ct)
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
		if resp.StatusCode != tc.want {
			t.Fatalf("%s: expected %d, got %d", tc.path, tc.want, resp.StatusCode)
		}
	}
}

func TestSetRateLimiter(t *testing.T) {
	s := &Server{}
	rl := NewRateLimiter(100, 10)
	s.SetRateLimiter(rl)
	if s.rl != rl {
		t.Fatal("rate limiter not set")
	}
	// Hit a 404 path to verify ratelimit fires
	w := httptest.NewRecorder()
	for i := 0; i < 12; i++ {
		r := httptest.NewRequest(http.MethodGet, "/nonexistent", nil)
		w = httptest.NewRecorder()
		s.ServeHTTP(w, r)
	}
	resp := w.Result()
	resp.Body.Close()
	if resp.StatusCode != http.StatusTooManyRequests {
		t.Fatalf("expected 429 after bursting, got %d", resp.StatusCode)
	}
}

func TestPublicOnlyHealthz(t *testing.T) {
	d := newTestDB(t)
	s := NewPublic(&internal.Config{}, d, testBundle)
	ts := httptest.NewServer(s)
	defer ts.Close()

	resp, err := http.Get(ts.URL + "/healthz")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}

	resp, err = http.Get(ts.URL + "/api/v1/cas")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("expected 401 without auth, got %d", resp.StatusCode)
	}

	resp, err = http.Get(ts.URL + "/pki/test.txt")
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
}

type noFlushWriter struct {
	http.ResponseWriter
}

func TestServeStatsSSENoFlusher(t *testing.T) {
	s := &Server{}
	// Must set a DB so collectStats doesn't panic
	d := newTestDB(t)
	s.cfgPtr.Store(&internal.Config{})
	s.dbPtr.Store(d)

	w := &noFlushWriter{httptest.NewRecorder()}
	r := httptest.NewRequest(http.MethodGet, "/", nil)
	s.apiStatsSSE(w, r)
	resp := w.ResponseWriter.(*httptest.ResponseRecorder).Result()
	resp.Body.Close()
	if resp.StatusCode != http.StatusInternalServerError {
		t.Fatalf("expected 500 without flusher, got %d", resp.StatusCode)
	}
}

func TestServeAPIBatchFastSkipsDB(t *testing.T) {
	srv := newTestServer(t)
	ts := httptest.NewServer(srv)
	defer ts.Close()

	body := `{"requests":[{"cn":"fast1.example.com","profile":"tls-server"},{"cn":"fast2.example.com","profile":"tls-server"}],"fast":true}`
	resp := authedPost(t, ts, "/api/certs/batch", "application/json", strings.NewReader(body))
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	var results []batchRespItem
	json.NewDecoder(resp.Body).Decode(&results)
	if len(results) != 2 {
		t.Fatalf("expected 2 results, got %d", len(results))
	}
	for _, r := range results {
		if r.Status != "ok" {
			t.Fatalf("expected ok for %s, got %s: %s", r.CN, r.Status, r.Error)
		}
	}

	// fast:true must NOT persist certs — verify via list API
	resp2 := authedGet(t, ts, "/api/v1/certs?ca=test-ca&cn=fast1.example.com&limit=10")
	defer resp2.Body.Close()
	var list struct {
		Certs []struct {
			CommonName string `json:"common_name"`
		} `json:"certs"`
	}
	json.NewDecoder(resp2.Body).Decode(&list)
	for _, c := range list.Certs {
		if strings.HasPrefix(c.CommonName, "fast") {
			t.Fatalf("fast batch cert %q unexpectedly persisted", c.CommonName)
		}
	}
}
